import type {
  MarketplaceData,
  MessagesData,
  Annonce,
  AnnonceResponse,
  Conversation,
  Message,
  Flag,
  MarketplaceTransaction,
} from '../_types/fan-supervision-types';

// ============================================
// MARKETPLACE MOCK DATA
// ============================================

export function generateMarketplaceData(fanId: string): MarketplaceData {
  const annonces: Annonce[] = [
    {
      id: 'A1234',
      title: 'Fitness coaching personnalisé',
      category: 'Sport & Bien-être',
      budget: { min: 50, max: 100 },
      deadline: '7 jours',
      status: 'active',
      responsesCount: 8,
      flags: [],
      createdAt: new Date('2025-10-15'),
    },
    {
      id: 'A1230',
      title: 'Montage vidéo YouTube',
      category: 'Création de contenu',
      budget: { min: 250, max: 250 },
      deadline: '7 jours',
      status: 'in_progress',
      responsesCount: 12,
      flags: [],
      createdAt: new Date('2025-10-10'),
      currentCreator: {
        id: '101',
        name: 'Emma Wilson',
        handle: 'video-pro-emma',
      },
    },
    {
      id: 'A1225',
      title: 'Photos privées demande inappropriée',
      category: 'Photographie',
      budget: { min: 500, max: 1000 },
      deadline: '3 jours',
      status: 'rejected',
      responsesCount: 2,
      flags: [
        {
          id: 'F-A1225-001',
          type: 'inappropriate_content',
          confidence: 94,
          keywords: ['private', 'photos', 'explicit'],
          severity: 'critical',
          recommendations: ['Reject annonce', 'Warn fan', 'Review account'],
          detectedAt: new Date('2025-10-05T14:30:00'),
          status: 'validated',
        },
        {
          id: 'F-A1225-002',
          type: 'price_manipulation',
          confidence: 78,
          keywords: ['cash', 'direct payment'],
          severity: 'warning',
          recommendations: ['Investigate', 'Monitor'],
          detectedAt: new Date('2025-10-05T14:32:00'),
          status: 'validated',
        },
      ],
      createdAt: new Date('2025-10-05'),
    },
    {
      id: 'A1220',
      title: 'Logo YouTube channel',
      category: 'Design graphique',
      budget: { min: 80, max: 80 },
      deadline: '5 jours',
      status: 'completed',
      responsesCount: 15,
      flags: [],
      createdAt: new Date('2025-09-20'),
      currentCreator: {
        id: '102',
        name: 'John Designer',
        handle: 'designer-john',
      },
      rating: 5,
    },
    {
      id: 'A1215',
      title: 'Rédaction articles de blog',
      category: 'Rédaction',
      budget: { min: 30, max: 50 },
      deadline: '10 jours',
      status: 'active',
      responsesCount: 6,
      flags: [],
      createdAt: new Date('2025-10-12'),
    },
    {
      id: 'A1210',
      title: 'Coaching nutrition',
      category: 'Sport & Bien-être',
      budget: { min: 120, max: 150 },
      deadline: '14 jours',
      status: 'completed',
      responsesCount: 10,
      flags: [],
      createdAt: new Date('2025-09-01'),
      currentCreator: {
        id: '103',
        name: 'Sophie Nutritionniste',
        handle: 'nutri-sophie',
      },
      rating: 4,
    },
    {
      id: 'A1205',
      title: 'Traduction anglais-français',
      category: 'Traduction',
      budget: { min: 40, max: 60 },
      deadline: '5 jours',
      status: 'expired',
      responsesCount: 3,
      flags: [],
      createdAt: new Date('2025-09-15'),
    },
    {
      id: 'A1200',
      title: 'Développement site web',
      category: 'Développement',
      budget: { min: 800, max: 1200 },
      deadline: '30 jours',
      status: 'in_progress',
      responsesCount: 20,
      flags: [],
      createdAt: new Date('2025-10-01'),
      currentCreator: {
        id: '104',
        name: 'Alexandre Dev',
        handle: 'dev-alex',
      },
    },
  ];

  return {
    annonces,
    totalAnnonces: annonces.length,
    totalResponses: annonces.reduce((sum, a) => sum + a.responsesCount, 0),
    ongoingTransactions: annonces.filter((a) => a.status === 'in_progress').length,
    detectedIncidents: annonces.reduce((sum, a) => sum + a.flags.length, 0),
    analytics: {
      completionRate: 75,
      averageTransactionAmount: 185,
      preferredCreators: [
        { id: '101', name: 'Emma Wilson', count: 3 },
        { id: '102', name: 'John Designer', count: 2 },
        { id: '103', name: 'Sophie Nutritionniste', count: 2 },
      ],
      favoriteCategories: [
        { category: 'Sport & Bien-être', count: 3 },
        { category: 'Création de contenu', count: 2 },
        { category: 'Design graphique', count: 2 },
      ],
      suspiciousPatterns: [
        'Tentatives de contact hors plateforme: 2',
        'Demandes inappropriées: 1',
      ],
    },
  };
}

export function generateAnnonceResponses(annonceId: string): AnnonceResponse[] {
  if (annonceId === 'A1234') {
    return [
      {
        id: 'R-001',
        annonceId: 'A1234',
        creatorId: 'C-001',
        creatorName: 'Sarah Fitness',
        creatorHandle: 'fitness-sarah',
        creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        creatorRating: 4.8,
        price: 75,
        deadline: '5 jours',
        message: 'Je suis coach certifiée avec 5 ans d\'expérience. Je peux vous proposer un programme personnalisé.',
        flags: [],
        submittedAt: new Date('2025-10-16T10:30:00'),
        status: 'pending',
      },
      {
        id: 'R-002',
        annonceId: 'A1234',
        creatorId: 'C-002',
        creatorName: 'Mike Coach',
        creatorHandle: 'coach-mike',
        creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
        creatorRating: 4.2,
        price: 120,
        deadline: '3 jours',
        message: 'Hi! I can help but let\'s talk on WhatsApp +33612345678. Payment via PayPal only €100.',
        flags: [
          {
            id: 'F-R002-001',
            type: 'payment_offsite',
            confidence: 96,
            keywords: ['PayPal', 'payment', 'only'],
            severity: 'critical',
            recommendations: ['Ban creator', 'Block response', 'Notify fan'],
            detectedAt: new Date('2025-10-16T11:15:00'),
            status: 'pending',
          },
          {
            id: 'F-R002-002',
            type: 'contact_external',
            confidence: 89,
            keywords: ['WhatsApp', 'phone number'],
            severity: 'critical',
            recommendations: ['Ban creator', 'Remove contact info'],
            detectedAt: new Date('2025-10-16T11:15:00'),
            status: 'pending',
          },
        ],
        submittedAt: new Date('2025-10-16T11:15:00'),
        status: 'pending',
      },
      {
        id: 'R-003',
        annonceId: 'A1234',
        creatorId: 'C-003',
        creatorName: 'Alex Trainer',
        creatorHandle: 'trainer-alex',
        creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        creatorRating: 4.6,
        price: 95,
        deadline: '7 jours',
        message: 'Programme sur mesure disponible. Voir mon site: fitnessweb.com pour plus d\'infos.',
        flags: [
          {
            id: 'F-R003-001',
            type: 'url_external',
            confidence: 75,
            keywords: ['site', 'fitnessweb.com'],
            severity: 'warning',
            recommendations: ['Warn creator', 'Remove URL', 'Monitor'],
            detectedAt: new Date('2025-10-16T14:20:00'),
            status: 'pending',
          },
        ],
        submittedAt: new Date('2025-10-16T14:20:00'),
        status: 'pending',
      },
      {
        id: 'R-004',
        annonceId: 'A1234',
        creatorId: 'C-004',
        creatorName: 'Julie Sport',
        creatorHandle: 'sport-julie',
        creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julie',
        creatorRating: 4.9,
        price: 85,
        deadline: '6 jours',
        message: 'Coaching fitness personnalisé avec suivi hebdomadaire inclus.',
        flags: [],
        submittedAt: new Date('2025-10-17T09:00:00'),
        status: 'pending',
      },
      {
        id: 'R-005',
        annonceId: 'A1234',
        creatorId: 'C-005',
        creatorName: 'Tom Wellness',
        creatorHandle: 'wellness-tom',
        creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
        creatorRating: 4.7,
        price: 90,
        deadline: '5 jours',
        message: 'Programme nutrition + fitness intégré. Portfolio disponible.',
        flags: [],
        submittedAt: new Date('2025-10-17T11:30:00'),
        status: 'pending',
      },
    ];
  }

  return [];
}

// ============================================
// MESSAGES MOCK DATA
// ============================================

export function generateMessagesData(fanId: string): MessagesData {
  const conversations: Conversation[] = [
    {
      id: 'CONV-001',
      type: 'subscription', // Abonnement normal
      creatorId: 'CR-001',
      creatorName: 'Suspicious Creator',
      creatorHandle: 'creator-x',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CreatorX',
      messagesCount: 8,
      flags: [
        {
          id: 'F1001',
          type: 'contact_external',
          confidence: 82,
          keywords: ['contact', 'private', 'outside'],
          severity: 'warning',
          recommendations: ['Monitor conversation', 'Warn creator'],
          detectedAt: new Date('2025-10-21T10:15:00'),
          status: 'pending',
        },
        {
          id: 'F1002',
          type: 'payment_offsite',
          confidence: 96,
          keywords: ['send money', 'outside platform'],
          severity: 'critical',
          recommendations: ['Ban creator immediately', 'Contact fan', 'Close conversation'],
          detectedAt: new Date('2025-10-22T16:20:00'),
          status: 'pending',
        },
      ],
      lastMessageAt: new Date('2025-10-22T17:00:00'),
      status: 'flagged',
      severity: 'critical',
    },
    {
      id: 'CONV-002',
      type: 'subscription', // Abonnement sain
      creatorId: 'CR-002',
      creatorName: 'Sarah Johnson',
      creatorHandle: 'sarah-johnson',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      messagesCount: 24,
      flags: [],
      lastMessageAt: new Date('2025-10-29T14:30:00'),
      status: 'active',
      severity: 'safe',
    },
    {
      id: 'CONV-003',
      type: 'marketplace', // Marketplace - commande vidéo
      creatorId: 'CR-003',
      creatorName: 'Emma Wilson',
      creatorHandle: 'video-pro-emma',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      messagesCount: 31,
      flags: [
        {
          id: 'F3001',
          type: 'creator_no_response_order',
          confidence: 89,
          keywords: ['pas de réponse', 'commande', 'deadline dépassé'],
          severity: 'warning',
          recommendations: ['Contact creator about order', 'Check delivery status'],
          detectedAt: new Date('2025-10-28T10:00:00'),
          status: 'pending',
        },
      ],
      lastMessageAt: new Date('2025-10-30T09:15:00'),
      status: 'flagged',
      severity: 'warning',
    },
    {
      id: 'CONV-004',
      type: 'marketplace', // Marketplace - design sain
      creatorId: 'CR-004',
      creatorName: 'John Designer',
      creatorHandle: 'designer-john',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      messagesCount: 18,
      flags: [],
      lastMessageAt: new Date('2025-09-25T16:45:00'),
      status: 'active',
      severity: 'safe',
    },
    {
      id: 'CONV-005',
      type: 'subscription', // Abonnement avec URL externe
      creatorId: 'CR-005',
      creatorName: 'Coach Suspicious',
      creatorHandle: 'coach-suspicious',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Coach',
      messagesCount: 15,
      flags: [
        {
          id: 'F2001',
          type: 'url_external',
          confidence: 71,
          keywords: ['check my website', 'link'],
          severity: 'warning',
          recommendations: ['Warn creator', 'Remove link'],
          detectedAt: new Date('2025-10-18T11:30:00'),
          status: 'pending',
        },
      ],
      lastMessageAt: new Date('2025-10-18T12:00:00'),
      status: 'flagged',
      severity: 'warning',
    },
    {
      id: 'CONV-006',
      type: 'marketplace', // Marketplace - Fan menace créateur
      creatorId: 'CR-006',
      creatorName: 'Photo Pro Mike',
      creatorHandle: 'photo-mike',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      messagesCount: 12,
      flags: [
        {
          id: 'F4001',
          type: 'fan_threat_refund',
          confidence: 93,
          keywords: ['avocat', 'poursuivre', 'remboursement immédiat'],
          severity: 'critical',
          recommendations: ['Contact fan - threat detected', 'Review marketplace order', 'Consider refund'],
          detectedAt: new Date('2025-10-26T14:20:00'),
          status: 'pending',
        },
      ],
      lastMessageAt: new Date('2025-10-26T15:00:00'),
      status: 'flagged',
      severity: 'critical',
    },
  ];

  const recentFlags: Flag[] = [
    {
      id: 'F1002',
      type: 'payment_offsite',
      confidence: 96,
      keywords: ['send money', 'outside platform'],
      severity: 'critical',
      recommendations: ['Ban creator immediately', 'Contact fan', 'Close conversation'],
      detectedAt: new Date('2025-10-22T16:20:00'),
      status: 'pending',
    },
    {
      id: 'F1001',
      type: 'contact_external',
      confidence: 82,
      keywords: ['contact', 'private', 'outside'],
      severity: 'warning',
      recommendations: ['Monitor conversation', 'Warn creator'],
      detectedAt: new Date('2025-10-21T10:15:00'),
      status: 'pending',
    },
    {
      id: 'F2001',
      type: 'url_external',
      confidence: 71,
      keywords: ['check my website', 'link'],
      severity: 'warning',
      recommendations: ['Warn creator', 'Remove link'],
      detectedAt: new Date('2025-10-18T11:30:00'),
      status: 'pending',
    },
  ];

  return {
    conversations,
    totalConversations: conversations.length,
    totalMessages: conversations.reduce((sum, c) => sum + c.messagesCount, 0),
    detectedFlags: conversations.reduce((sum, c) => sum + c.flags.length, 0),
    adminInterventions: 2,
    recentFlags,
    aiStats: {
      accuracy: 87,
      totalDetections: 45,
      validatedFlags: 32,
      ignoredFlags: 13,
    },
  };
}

export function generateConversationMessages(conversationId: string): Message[] {
  if (conversationId === 'CONV-001') {
    return [
      {
        id: 'M-001',
        conversationId: 'CONV-001',
        from: 'creator',
        content: 'Salut Robert ! Merci pour ton intérêt dans mon service.',
        timestamp: new Date('2025-10-20T14:23:00'),
        read: true,
        flags: [],
        deleted: false,
      },
      {
        id: 'M-002',
        conversationId: 'CONV-001',
        from: 'fan',
        content: 'Hello ! Ton portfolio est vraiment top 👍',
        timestamp: new Date('2025-10-20T14:45:00'),
        read: true,
        flags: [],
        deleted: false,
      },
      {
        id: 'M-003',
        conversationId: 'CONV-001',
        from: 'creator',
        content: 'On peut discuter en privé ? Contact privé serait mieux.',
        timestamp: new Date('2025-10-21T10:15:00'),
        read: true,
        flags: [
          {
            id: 'F1001',
            type: 'contact_external',
            confidence: 82,
            keywords: ['contact', 'private', 'outside'],
            severity: 'warning',
            recommendations: ['Monitor conversation', 'Warn creator'],
            detectedAt: new Date('2025-10-21T10:15:00'),
            status: 'pending',
          },
        ],
        deleted: false,
      },
      {
        id: 'M-004',
        conversationId: 'CONV-001',
        from: 'fan',
        content: 'C\'est-à-dire ? On ne peut pas discuter ici ?',
        timestamp: new Date('2025-10-21T10:30:00'),
        read: true,
        flags: [],
        deleted: false,
      },
      {
        id: 'M-005',
        conversationId: 'CONV-001',
        from: 'creator',
        content: 'Send money outside platform 💰 I take PayPal, it\'s easier and cheaper',
        timestamp: new Date('2025-10-22T16:20:00'),
        read: true,
        flags: [
          {
            id: 'F1002',
            type: 'payment_offsite',
            confidence: 96,
            keywords: ['send money', 'outside platform', 'PayPal'],
            severity: 'critical',
            recommendations: ['Ban creator immediately', 'Contact fan', 'Close conversation'],
            detectedAt: new Date('2025-10-22T16:20:00'),
            status: 'pending',
          },
        ],
        deleted: false,
      },
      {
        id: 'M-006',
        conversationId: 'CONV-001',
        from: 'fan',
        content: 'Je préfère rester sur la plateforme pour être protégé.',
        timestamp: new Date('2025-10-22T16:45:00'),
        read: true,
        flags: [],
        deleted: false,
      },
      {
        id: 'M-007',
        conversationId: 'CONV-001',
        from: 'creator',
        content: 'Ok no problem, on fait comme tu veux',
        timestamp: new Date('2025-10-22T17:00:00'),
        read: true,
        flags: [],
        deleted: false,
      },
      {
        id: 'M-008',
        conversationId: 'CONV-001',
        from: 'fan',
        content: 'Parfait ! On continue ici alors.',
        timestamp: new Date('2025-10-22T17:05:00'),
        read: false,
        flags: [],
        deleted: false,
      },
    ];
  }

  // Default empty conversation
  return [];
}

// ============================================
// MARKETPLACE TRANSACTIONS MOCK DATA
// ============================================

export const marketplaceTransactions: MarketplaceTransaction[] = [
  {
    id: 'MT-001',
    annonceId: 'A1234',
    annonceTitle: 'Montage vidéo YouTube professionnelle',
    creatorId: 'creator-emma-001',
    creatorUsername: '@video-pro-emma',
    amount: 250.0,
    status: 'in_progress',
    statusLabel: 'En cours',
    date: new Date('2025-10-25T10:30:00').toISOString(),
    deliveryDate: new Date('2025-11-05T23:59:59').toISOString(),
  },
  {
    id: 'MT-002',
    annonceId: 'A1225',
    annonceTitle: 'Création logo YouTube personnalisé',
    creatorId: 'creator-john-002',
    creatorUsername: '@designer-john',
    amount: 80.0,
    status: 'completed',
    statusLabel: 'Terminée',
    date: new Date('2025-10-15T14:20:00').toISOString(),
    deliveryDate: new Date('2025-10-20T18:45:00').toISOString(),
    rating: 5,
  },
  {
    id: 'MT-003',
    annonceId: 'A1226',
    annonceTitle: 'Coaching fitness personnalisé 1 mois',
    creatorId: 'creator-sarah-003',
    creatorUsername: '@fitness-sarah',
    amount: 75.0,
    status: 'completed',
    statusLabel: 'Terminée',
    date: new Date('2025-09-20T09:15:00').toISOString(),
    deliveryDate: new Date('2025-10-20T23:59:59').toISOString(),
    rating: 5,
  },
  {
    id: 'MT-004',
    annonceId: 'A1227',
    annonceTitle: 'Animation logo 3D pour intro vidéo',
    creatorId: 'creator-3d-004',
    creatorUsername: '@creator-3d',
    amount: 120.0,
    status: 'cancelled',
    statusLabel: 'Annulée',
    date: new Date('2025-10-10T16:40:00').toISOString(),
  },
  {
    id: 'MT-005',
    annonceId: 'A1228',
    annonceTitle: 'Retouche photos professionnelles (pack 10)',
    creatorId: 'creator-photo-005',
    creatorUsername: '@photo-editor',
    amount: 45.0,
    status: 'refunded',
    statusLabel: 'Remboursée',
    date: new Date('2025-09-05T11:25:00').toISOString(),
    deliveryDate: new Date('2025-09-10T14:30:00').toISOString(),
  },
];

// ============================================
// FAN MARKETPLACE PURCHASES (Direct purchases)
// ============================================

export function generateMarketplacePurchases(userId: string): any[] {
  return [
    {
      id: 'PURCH-001',
      annonceId: 'ANN-SARAH-001',
      annonceTitle: 'Programme fitness 4 semaines',
      creatorId: '100',
      creatorUsername: '@sarah-johnson',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      amount: 75.0,
      purchaseDate: new Date('2025-09-15T10:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-10-13T23:59:59').toISOString(),
      deliveredAt: new Date('2025-10-10T14:30:00').toISOString(),
      rating: 5,
      flags: [],
    },
    {
      id: 'PURCH-002',
      annonceId: 'ANN-VIDEO-002',
      annonceTitle: 'Montage vidéo professionnel',
      creatorId: 'creator-video-001',
      creatorUsername: '@video-creator',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VideoCreator',
      amount: 120.0,
      purchaseDate: new Date('2025-10-25T14:20:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-10-30T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'PURCH-003',
      annonceId: 'ANN-DESIGN-003',
      annonceTitle: 'Logo personnalisé + variations',
      creatorId: 'creator-designer-001',
      creatorUsername: '@designer-x',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DesignerX',
      amount: 80.0,
      purchaseDate: new Date('2025-10-18T09:15:00').toISOString(),
      status: 'delivered',
      deliveryDeadline: new Date('2025-10-25T23:59:59').toISOString(),
      deliveredAt: new Date('2025-10-20T16:45:00').toISOString(),
      flags: [],
    },
    {
      id: 'PURCH-004',
      annonceId: 'ANN-NUTRITION-004',
      annonceTitle: 'Coaching nutrition 1 mois',
      creatorId: 'creator-nutrition-001',
      creatorUsername: '@nutritionist-pro',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nutritionist',
      amount: 99.0,
      purchaseDate: new Date('2025-10-20T11:30:00').toISOString(),
      status: 'disputed',
      deliveryDeadline: new Date('2025-11-20T23:59:59').toISOString(),
      flags: ['quality_issue', 'late_delivery'],
    },
    {
      id: 'PURCH-005',
      annonceId: 'ANN-EBOOK-005',
      annonceTitle: 'E-book 50 recettes healthy',
      creatorId: 'creator-chef-001',
      creatorUsername: '@chef-creator',
      creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chef',
      amount: 19.99,
      purchaseDate: new Date('2025-10-10T15:45:00').toISOString(),
      status: 'refunded',
      deliveryDeadline: new Date('2025-10-12T23:59:59').toISOString(),
      flags: ['not_delivered'],
    },
  ];
}

// ============================================
// CREATOR MARKETPLACE DATA GENERATORS
// ============================================

export function generateCreatorAnnonces(userId: string): any[] {
  return [
    // ACTIVE ANNONCES (3)
    {
      id: 'CA-001',
      title: 'Coaching fitness personnalisé 4 semaines',
      description: 'Programme complet avec suivi quotidien, plan alimentaire et 3 appels vidéo par semaine',
      category: 'Fitness & Santé',
      budget: { min: 200, max: 350 },
      deadline: '4 semaines',
      status: 'active',
      viewsCount: 156,
      responsesCount: 12,
      createdAt: new Date('2025-10-01T10:00:00'),
      flags: [],
    },
    {
      id: 'CA-002',
      title: 'Montage vidéo YouTube professionnel',
      description: 'Montage complet avec transitions, effets, musique, miniature et optimisation SEO',
      category: 'Vidéo & Montage',
      budget: { min: 100, max: 200 },
      deadline: '1 semaine',
      status: 'active',
      viewsCount: 89,
      responsesCount: 8,
      createdAt: new Date('2025-10-15T14:30:00'),
      flags: [],
    },
    {
      id: 'CA-003',
      title: 'Consultation nutrition 1h + plan repas',
      description: 'Bilan nutritionnel complet, plan personnalisé sur 2 semaines, liste courses incluse',
      category: 'Nutrition & Diététique',
      budget: { min: 80, max: 120 },
      deadline: '3 jours',
      status: 'active',
      viewsCount: 234,
      responsesCount: 18,
      createdAt: new Date('2025-10-20T09:15:00'),
      flags: [],
    },

    // DRAFT ANNONCES (2)
    {
      id: 'CA-004',
      title: 'Formation trading crypto débutants',
      description: 'Cours complet 8h, stratégies, analyse technique, gestion risque',
      category: 'Finance & Crypto',
      budget: { min: 300, max: 500 },
      deadline: '2 mois',
      status: 'draft',
      viewsCount: 0,
      responsesCount: 0,
      createdAt: new Date('2025-10-25T16:00:00'),
      flags: ['awaiting_review'],
    },
    {
      id: 'CA-005',
      title: 'Pack 3 photos professionnelles retouchées',
      description: 'Shooting photo 1h, 3 photos haute résolution retouchées, usage commercial',
      category: 'Photographie',
      budget: { min: 150, max: 250 },
      deadline: '1 semaine',
      status: 'draft',
      viewsCount: 0,
      responsesCount: 0,
      createdAt: new Date('2025-10-26T11:20:00'),
      flags: [],
    },

    // CLOSED ANNONCES (3)
    {
      id: 'CA-006',
      title: 'Logo + charte graphique complète',
      description: '3 propositions logo, déclinaisons, charte couleurs, typographie',
      category: 'Design Graphique',
      budget: { min: 400, max: 600 },
      deadline: '2 semaines',
      status: 'closed',
      viewsCount: 312,
      responsesCount: 24,
      createdAt: new Date('2025-09-15T08:00:00'),
      flags: [],
    },
    {
      id: 'CA-007',
      title: 'Rédaction articles blog SEO (lot 5)',
      description: '5 articles 800 mots, optimisés SEO, recherche keywords, relecture',
      category: 'Rédaction & SEO',
      budget: { min: 250, max: 350 },
      deadline: '10 jours',
      status: 'closed',
      viewsCount: 178,
      responsesCount: 15,
      createdAt: new Date('2025-09-10T13:45:00'),
      flags: [],
    },
    {
      id: 'CA-008',
      title: 'Cours particuliers maths lycée (pack 10h)',
      description: '10 séances 1h, niveau Terminale, préparation bac, exercices inclus',
      category: 'Éducation & Cours',
      budget: { min: 300, max: 400 },
      deadline: '1 mois',
      status: 'closed',
      viewsCount: 67,
      responsesCount: 5,
      createdAt: new Date('2025-08-20T10:30:00'),
      flags: [],
    },
  ];
}

export function generateCreatorDemands(userId: string): any[] {
  return [
    // ACCEPTED RESPONSES (5)
    {
      id: 'CD-001',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-001',
      fanName: 'Marie Dubois',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marie',
      fanBudget: { min: 250, max: 300 },
      requestMessage: 'Je recherche un coaching complet pour perdre 5kg et me tonifier avant l\'été. Disponible le soir.',
      requestedAt: new Date('2025-10-05T14:20:00'),
      myResponse: {
        id: 'RESP-001',
        price: 280,
        deadline: '28 jours',
        message: 'Parfait ! Je vous propose un programme complet avec 3 appels/semaine en soirée, plan nutritionnel personnalisé et suivi quotidien via WhatsApp.',
        submittedAt: new Date('2025-10-05T16:45:00'),
        status: 'accepted',
      },
      flags: [],
    },
    {
      id: 'CD-002',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-002',
      fanName: 'Thomas Martin',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas',
      fanBudget: { min: 120, max: 150 },
      requestMessage: 'Besoin de monter mes vidéos gaming (15-20min), transitions dynamiques, intro/outro.',
      requestedAt: new Date('2025-10-16T09:30:00'),
      myResponse: {
        id: 'RESP-002',
        price: 135,
        deadline: '5 jours',
        message: 'Super ! Je peux créer un montage dynamique avec transitions, effets sonores, miniature custom et optimisation pour YouTube.',
        submittedAt: new Date('2025-10-16T11:15:00'),
        status: 'accepted',
      },
      flags: [],
    },
    {
      id: 'CD-003',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-003',
      fanName: 'Sophie Bernard',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
      fanBudget: { min: 90, max: 110 },
      requestMessage: 'Je veux un rééquilibrage alimentaire, je suis végétarienne. Intolérante au lactose.',
      requestedAt: new Date('2025-10-21T10:00:00'),
      myResponse: {
        id: 'RESP-003',
        price: 95,
        deadline: '2 jours',
        message: 'Pas de souci ! Je suis spécialisée en nutrition végétarienne. Consultation 1h Zoom + plan 14 jours adapté sans lactose.',
        submittedAt: new Date('2025-10-21T11:30:00'),
        status: 'accepted',
      },
      flags: [],
    },
    {
      id: 'CD-004',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-004',
      fanName: 'Lucas Petit',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
      fanBudget: { min: 220, max: 270 },
      requestMessage: 'Je veux prendre de la masse musculaire, débutant en musculation.',
      requestedAt: new Date('2025-10-08T17:00:00'),
      myResponse: {
        id: 'RESP-004',
        price: 250,
        deadline: '30 jours',
        message: 'Excellent ! Programme prise de masse sur 4 semaines : 4 séances/semaine, plan nutritionnel hypercalorique, vidéos exercices.',
        submittedAt: new Date('2025-10-08T18:20:00'),
        status: 'accepted',
      },
      flags: [],
    },
    {
      id: 'CD-005',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-005',
      fanName: 'Emma Rousseau',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      fanBudget: { min: 150, max: 180 },
      requestMessage: 'Montage vidéo beauté/lifestyle 10-12min, besoin d\'un style élégant et épuré.',
      requestedAt: new Date('2025-10-18T13:45:00'),
      myResponse: {
        id: 'RESP-005',
        price: 165,
        deadline: '4 jours',
        message: 'Parfait ! Je ferai un montage élégant avec transitions douces, color grading professionnel et typographies modernes.',
        submittedAt: new Date('2025-10-18T15:00:00'),
        status: 'accepted',
      },
      flags: [],
    },

    // PENDING RESPONSES (4)
    {
      id: 'CD-006',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-006',
      fanName: 'Alexandre Moreau',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexandre',
      fanBudget: { min: 100, max: 120 },
      requestMessage: 'Je fais beaucoup de sport (crossfit 5x/semaine), besoin plan nutrition adapté.',
      requestedAt: new Date('2025-10-27T08:30:00'),
      myResponse: {
        id: 'RESP-006',
        price: 110,
        deadline: '2 jours',
        message: 'Super ! Consultation 1h + plan nutrition sportif avec timing macros pré/post-training.',
        submittedAt: new Date('2025-10-27T10:00:00'),
        status: 'pending',
      },
      flags: [],
    },
    {
      id: 'CD-007',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-007',
      fanName: 'Chloé Laurent',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe',
      fanBudget: { min: 200, max: 250 },
      requestMessage: 'Reprise sport après grossesse, besoin accompagnement bienveillant.',
      requestedAt: new Date('2025-10-28T16:00:00'),
      myResponse: {
        id: 'RESP-007',
        price: 240,
        deadline: '4 semaines',
        message: 'Bravo pour cette démarche ! Programme post-natal adapté, renforcement périnée, exercices doux.',
        submittedAt: new Date('2025-10-28T17:30:00'),
        status: 'pending',
      },
      flags: [],
    },
    {
      id: 'CD-008',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-008',
      fanName: 'Hugo Simon',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo',
      fanBudget: { min: 80, max: 120 },
      requestMessage: 'Vidéos tech reviews 8-10min, montage rapide avec comparaisons produits.',
      requestedAt: new Date('2025-10-29T11:20:00'),
      myResponse: {
        id: 'RESP-008',
        price: 105,
        deadline: '3 jours',
        message: 'Ok ! Montage dynamique avec split-screens pour comparaisons, animations specs produits.',
        submittedAt: new Date('2025-10-29T12:45:00'),
        status: 'pending',
      },
      flags: [],
    },
    {
      id: 'CD-009',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-009',
      fanName: 'Léa Durand',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lea',
      fanBudget: { min: 85, max: 100 },
      requestMessage: 'Conseils nutrition pour mieux dormir, je grignote le soir.',
      requestedAt: new Date('2025-10-30T09:00:00'),
      myResponse: {
        id: 'RESP-009',
        price: 90,
        deadline: '1 jour',
        message: 'Consultation ciblée sur gestion fringales nocturnes + aliments favorisant le sommeil.',
        submittedAt: new Date('2025-10-30T10:15:00'),
        status: 'pending',
      },
      flags: [],
    },

    // REJECTED RESPONSES (2)
    {
      id: 'CD-010',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-010',
      fanName: 'Nathan Girard',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nathan',
      fanBudget: { min: 150, max: 200 },
      requestMessage: 'Programme musculation maison, pas de matériel.',
      requestedAt: new Date('2025-10-12T14:00:00'),
      myResponse: {
        id: 'RESP-010',
        price: 320,
        deadline: '4 semaines',
        message: 'Programme complet poids du corps avec matériel minimal (bandes élastiques recommandées).',
        submittedAt: new Date('2025-10-12T15:30:00'),
        status: 'rejected',
      },
      flags: [],
    },
    {
      id: 'CD-011',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-011',
      fanName: 'Camille Blanc',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camille',
      fanBudget: { min: 60, max: 90 },
      requestMessage: 'Montage simple vidéo 5min, juste couper les blancs.',
      requestedAt: new Date('2025-10-22T10:30:00'),
      myResponse: {
        id: 'RESP-011',
        price: 180,
        deadline: '1 semaine',
        message: 'Je propose un montage professionnel complet avec effets et transitions premium.',
        submittedAt: new Date('2025-10-22T11:45:00'),
        status: 'rejected',
      },
      flags: [],
    },

    // NO RESPONSE YET (1)
    {
      id: 'CD-012',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-012',
      fanName: 'Mathis Lefebvre',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mathis',
      fanBudget: { min: 70, max: 90 },
      requestMessage: 'Étudiant, petit budget, besoin conseils nutrition équilibrée pas chère.',
      requestedAt: new Date('2025-10-31T07:45:00'),
      myResponse: undefined,
      flags: [],
    },
  ];
}

export function generateCreatorOrders(userId: string): any[] {
  return [
    // ACTIVE ORDERS - IN PROGRESS (8)
    {
      id: 'CO-001',
      type: 'fan_demand',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-001',
      fanName: 'Marie Dubois',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marie',
      amount: 280,
      startDate: new Date('2025-10-06T09:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-03T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-002',
      type: 'fan_demand',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-002',
      fanName: 'Thomas Martin',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas',
      amount: 135,
      startDate: new Date('2025-10-17T10:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-02T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-003',
      type: 'direct_purchase',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-013',
      fanName: 'Julie Garnier',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julie',
      amount: 95,
      startDate: new Date('2025-10-25T14:30:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-01T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-004',
      type: 'fan_demand',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-004',
      fanName: 'Lucas Petit',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
      amount: 250,
      startDate: new Date('2025-10-09T08:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-08T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-005',
      type: 'direct_purchase',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-014',
      fanName: 'Antoine Roy',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Antoine',
      amount: 120,
      startDate: new Date('2025-10-26T11:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-05T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-006',
      type: 'fan_demand',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-005',
      fanName: 'Emma Rousseau',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      amount: 165,
      startDate: new Date('2025-10-19T09:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-03T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-007',
      type: 'direct_purchase',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-015',
      fanName: 'Sarah Cohen',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      amount: 300,
      startDate: new Date('2025-10-20T16:00:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-17T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-008',
      type: 'direct_purchase',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-016',
      fanName: 'Pierre Dubois',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pierre',
      amount: 100,
      startDate: new Date('2025-10-28T10:30:00').toISOString(),
      status: 'in_progress',
      deliveryDeadline: new Date('2025-11-04T23:59:59').toISOString(),
      flags: [],
    },

    // PENDING ORDERS (3)
    {
      id: 'CO-009',
      type: 'fan_demand',
      annonceId: 'CA-003',
      annonceTitle: 'Consultation nutrition 1h + plan repas',
      fanId: 'fan-003',
      fanName: 'Sophie Bernard',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
      amount: 95,
      startDate: new Date('2025-10-22T09:00:00').toISOString(),
      status: 'pending',
      deliveryDeadline: new Date('2025-11-01T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-010',
      type: 'direct_purchase',
      annonceId: 'CA-002',
      annonceTitle: 'Montage vidéo YouTube professionnel',
      fanId: 'fan-017',
      fanName: 'Laura Martin',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
      amount: 140,
      startDate: new Date('2025-10-30T15:00:00').toISOString(),
      status: 'pending',
      deliveryDeadline: new Date('2025-11-09T23:59:59').toISOString(),
      flags: [],
    },
    {
      id: 'CO-011',
      type: 'direct_purchase',
      annonceId: 'CA-001',
      annonceTitle: 'Coaching fitness personnalisé 4 semaines',
      fanId: 'fan-018',
      fanName: 'Kevin Leroy',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
      amount: 275,
      startDate: new Date('2025-10-31T11:30:00').toISOString(),
      status: 'pending',
      deliveryDeadline: new Date('2025-11-28T23:59:59').toISOString(),
      flags: [],
    },

    // DELIVERED ORDERS (3)
    {
      id: 'CO-012',
      type: 'fan_demand',
      annonceId: 'CA-006',
      annonceTitle: 'Logo + charte graphique complète',
      fanId: 'fan-019',
      fanName: 'Nicolas Bonnet',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nicolas',
      amount: 480,
      startDate: new Date('2025-09-20T10:00:00').toISOString(),
      status: 'delivered',
      deliveryDeadline: new Date('2025-10-04T23:59:59').toISOString(),
      deliveredAt: new Date('2025-10-02T16:30:00').toISOString(),
      flags: [],
    },
    {
      id: 'CO-013',
      type: 'direct_purchase',
      annonceId: 'CA-007',
      annonceTitle: 'Rédaction articles blog SEO (lot 5)',
      fanId: 'fan-020',
      fanName: 'Isabelle Perrin',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabelle',
      amount: 290,
      startDate: new Date('2025-09-12T14:00:00').toISOString(),
      status: 'delivered',
      deliveryDeadline: new Date('2025-09-22T23:59:59').toISOString(),
      deliveredAt: new Date('2025-09-20T10:15:00').toISOString(),
      flags: [],
    },
    {
      id: 'CO-014',
      type: 'fan_demand',
      annonceId: 'CA-007',
      annonceTitle: 'Rédaction articles blog SEO (lot 5)',
      fanId: 'fan-021',
      fanName: 'Olivier Dubois',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivier',
      amount: 310,
      startDate: new Date('2025-09-25T09:00:00').toISOString(),
      status: 'delivered',
      deliveryDeadline: new Date('2025-10-05T23:59:59').toISOString(),
      deliveredAt: new Date('2025-10-04T14:20:00').toISOString(),
      flags: [],
    },

    // COMPLETED ORDERS (5 with ratings)
    {
      id: 'CO-015',
      type: 'fan_demand',
      annonceId: 'CA-006',
      annonceTitle: 'Logo + charte graphique complète',
      fanId: 'fan-022',
      fanName: 'Céline Lambert',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Celine',
      amount: 520,
      startDate: new Date('2025-09-01T10:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-09-15T23:59:59').toISOString(),
      deliveredAt: new Date('2025-09-13T11:00:00').toISOString(),
      rating: 5,
      review: 'Travail exceptionnel ! Sarah est très à l\'écoute et professionnelle. Le logo dépasse mes attentes !',
      flags: [],
    },
    {
      id: 'CO-016',
      type: 'direct_purchase',
      annonceId: 'CA-008',
      annonceTitle: 'Cours particuliers maths lycée (pack 10h)',
      fanId: 'fan-023',
      fanName: 'Julien Mercier',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julien',
      amount: 350,
      startDate: new Date('2025-08-25T09:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-09-25T23:59:59').toISOString(),
      deliveredAt: new Date('2025-09-22T18:00:00').toISOString(),
      rating: 5,
      review: 'Mon fils a progressé incroyablement ! Pédagogie excellente, très patient. Merci beaucoup !',
      flags: [],
    },
    {
      id: 'CO-017',
      type: 'fan_demand',
      annonceId: 'CA-007',
      annonceTitle: 'Rédaction articles blog SEO (lot 5)',
      fanId: 'fan-024',
      fanName: 'Stéphanie Roux',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Stephanie',
      amount: 280,
      startDate: new Date('2025-08-15T14:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-08-25T23:59:59').toISOString(),
      deliveredAt: new Date('2025-08-24T09:30:00').toISOString(),
      rating: 4,
      review: 'Bon travail, articles bien rédigés. Juste un petit retard sur la livraison mais qualité au rendez-vous.',
      flags: [],
    },
    {
      id: 'CO-018',
      type: 'direct_purchase',
      annonceId: 'CA-006',
      annonceTitle: 'Logo + charte graphique complète',
      fanId: 'fan-025',
      fanName: 'Vincent Faure',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vincent',
      amount: 450,
      startDate: new Date('2025-08-10T11:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-08-24T23:59:59').toISOString(),
      deliveredAt: new Date('2025-08-23T15:45:00').toISOString(),
      rating: 5,
      review: 'Créative, réactive, professionnelle. Le logo est parfait pour ma marque. Je recommande vivement !',
      flags: [],
    },
    {
      id: 'CO-019',
      type: 'fan_demand',
      annonceId: 'CA-008',
      annonceTitle: 'Cours particuliers maths lycée (pack 10h)',
      fanId: 'fan-026',
      fanName: 'Sandrine Petit',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sandrine',
      amount: 380,
      startDate: new Date('2025-07-20T10:00:00').toISOString(),
      status: 'completed',
      deliveryDeadline: new Date('2025-08-20T23:59:59').toISOString(),
      deliveredAt: new Date('2025-08-18T17:00:00').toISOString(),
      rating: 5,
      review: 'Ma fille a eu 16/20 au bac grâce à Sarah ! Explications claires, exercices adaptés. Top !',
      flags: [],
    },

    // DISPUTED ORDER (1)
    {
      id: 'CO-020',
      type: 'direct_purchase',
      annonceId: 'CA-007',
      annonceTitle: 'Rédaction articles blog SEO (lot 5)',
      fanId: 'fan-027',
      fanName: 'Patrick Lefevre',
      fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patrick',
      amount: 270,
      startDate: new Date('2025-09-05T13:00:00').toISOString(),
      status: 'disputed',
      deliveryDeadline: new Date('2025-09-15T23:59:59').toISOString(),
      flags: ['quality_issue', 'communication_problem'],
    },
  ];
}

export function generateCreatorReputation(userId: string): any {
  return {
    averageRating: 4.8,
    totalReviews: 27,
    completionRate: 94,
    averageDeliveryTime: 11, // days
    satisfactionRate: 96,
    recentRatings: [
      { orderId: 'CO-015', rating: 5, date: new Date('2025-09-14T12:00:00').toISOString() },
      { orderId: 'CO-016', rating: 5, date: new Date('2025-09-23T10:00:00').toISOString() },
      { orderId: 'CO-017', rating: 4, date: new Date('2025-08-25T15:00:00').toISOString() },
      { orderId: 'CO-018', rating: 5, date: new Date('2025-08-24T09:00:00').toISOString() },
      { orderId: 'CO-019', rating: 5, date: new Date('2025-08-19T11:00:00').toISOString() },
      { orderId: 'CO-031', rating: 4, date: new Date('2025-07-30T14:00:00').toISOString() },
      { orderId: 'CO-032', rating: 5, date: new Date('2025-07-22T16:00:00').toISOString() },
      { orderId: 'CO-033', rating: 5, date: new Date('2025-07-15T13:00:00').toISOString() },
      { orderId: 'CO-034', rating: 4, date: new Date('2025-07-08T10:00:00').toISOString() },
      { orderId: 'CO-035', rating: 5, date: new Date('2025-07-01T17:00:00').toISOString() },
    ],
    recentReviews: [
      {
        orderId: 'CO-015',
        fanName: 'Céline Lambert',
        fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Celine',
        rating: 5,
        review: 'Travail exceptionnel ! Sarah est très à l\'écoute et professionnelle. Le logo dépasse mes attentes !',
        date: new Date('2025-09-14T12:00:00').toISOString(),
      },
      {
        orderId: 'CO-016',
        fanName: 'Julien Mercier',
        fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Julien',
        rating: 5,
        review: 'Mon fils a progressé incroyablement ! Pédagogie excellente, très patient. Merci beaucoup !',
        date: new Date('2025-09-23T10:00:00').toISOString(),
      },
      {
        orderId: 'CO-017',
        fanName: 'Stéphanie Roux',
        fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Stephanie',
        rating: 4,
        review: 'Bon travail, articles bien rédigés. Juste un petit retard sur la livraison mais qualité au rendez-vous.',
        date: new Date('2025-08-25T15:00:00').toISOString(),
      },
      {
        orderId: 'CO-018',
        fanName: 'Vincent Faure',
        fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vincent',
        rating: 5,
        review: 'Créative, réactive, professionnelle. Le logo est parfait pour ma marque. Je recommande vivement !',
        date: new Date('2025-08-24T09:00:00').toISOString(),
      },
      {
        orderId: 'CO-019',
        fanName: 'Sandrine Petit',
        fanAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sandrine',
        rating: 5,
        review: 'Ma fille a eu 16/20 au bac grâce à Sarah ! Explications claires, exercices adaptés. Top !',
        date: new Date('2025-08-19T11:00:00').toISOString(),
      },
    ],
  };
}

export function generateCreatorMarketplaceData(userId: string): any {
  const annonces = generateCreatorAnnonces(userId);
  const demands = generateCreatorDemands(userId);
  const orders = generateCreatorOrders(userId);
  const reputation = generateCreatorReputation(userId);

  return {
    annonces,
    demands,
    orders,
    reputation,
    stats: {
      totalAnnonces: annonces.length,
      activeAnnonces: annonces.filter((a: any) => a.status === 'active').length,
      totalDemands: demands.length,
      activeOrders: orders.filter((o: any) => o.status === 'in_progress' || o.status === 'pending').length,
      completedOrders: orders.filter((o: any) => o.status === 'completed').length,
    },
  };
}
